language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-yii-environment' ]; then cd .. && eval "mv $currentfolder generator-yii-environment" && cd generator-yii-environment; fi

